//app/layout.js
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Budget With Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Other meta tags as needed */}
      </Head>
      <html lang="en">
        <body className={inter.className}> 
          <header className="w-full">
            {/* <nav className="flex justify-center space-x-4">
              <Link href="/" className="text-black hover:text-blue-500">
                Home
              </Link>
              <Link href="/management" className="text-black hover:text-blue-500">
                Management
              </Link>
            </nav> */}
          </header>
          {children}
          <footer className="text-center">&copy; TC - Budget With Me - Module 3</footer>
        </body>
      </html>
    </>
  );
}
